# Generated by Django 4.2.7 on 2025-11-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('in-person', 'In-Person')], default='video', max_length=20),
        ),
    ]
